### ISSUE TITLE
리뷰 모달 요청 기능 관련해서 특정 meetup은 더이상 반환하지 않는 API를 구현한다.

### ISSUE THREAD

**Issue by chlqls** [KUDDY-2023/KUDDY-back#156]
## 🤷 구현할 기능
프론트 피드백 반영해서 리뷰 모달 요청 시 특정 spot은 더이상 반환하지 않도록 API 추가한다.

## 🔨 상세 작업 내용

- [ ] 프론트에서 meetupId 보내면 더이상 리뷰 모달 요청 시 특정 meetup의 리뷰 모달이 반환되지 않도록 API를 구현한다.

## ⏰ 예상 소요 기간
~10/13(금)

**Comment by june0216** [comment]
meetup 이후 3일간만 확인하면 즉, ‘오늘하루동안 보지않기’ 같은 기능들이 프론트에서 쿠키를 이용해서 구현하므로 백에서는 구현하지 않기로 함
